name-template: "$RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&'

categories:
  - title: "Changed"
    labels:
      - feature
      - enhancement
      - backend
      - frontend
      - formula
      - docs
      - ci
      - scripts
  - title: "Fixed"
    labels:
      - bug
      - fix
  - title: "Dependencies"
    labels:
      - dependencies

template: |
  $CHANGES

version-resolver:
  major:
    labels:
      - major
  minor:
    labels:
      - feature
      - enhancement
  patch:
    labels:
      - bug
      - fix
      - dependencies
      - backend
      - frontend
      - formula
      - docs
      - ci
      - scripts
  default: patch
